services:
  postgres:
    image: postgres:17
    container_name: marketstack-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: MarketStack_Dev
      POSTGRES_USER: Marketstack
      POSTGRES_PASSWORD: MarketStack

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: