// <auto-generated />
using System;
using MarketStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketStack.Data.Migrations
{
    [DbContext(typeof(MarketStackContext))]
    [Migration("20260718153728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchasedAt");

                    b.Property<int>("StoreLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("store_location_id");

                    b.HasKey("Id");

                    b.HasIndex("StoreLocationId");

                    b.ToTable("receipt", (string)null);
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.ReceiptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_price");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("net_price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_id");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("receipt_item", (string)null);
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.ReceiptTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("GrossTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("gros_total");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("net_total");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_total");

                    b.Property<decimal>("VatTypeATotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_type_A_total");

                    b.Property<decimal>("VatTypeBTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vat_type_B_total");

                    b.HasKey("Id");

                    b.ToTable("receipt_total", (string)null);
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.StoreChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("store_chain", (string)null);
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.StoreLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<int>("StoreChainId")
                        .HasColumnType("integer")
                        .HasColumnName("store_chain_id");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id");

                    b.HasIndex("StoreChainId");

                    b.ToTable("store_location", (string)null);
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.Receipt", b =>
                {
                    b.HasOne("MarketStack.Data.Contracts.Entities.StoreLocation", "StoreLocation")
                        .WithMany("Receipts")
                        .HasForeignKey("StoreLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreLocation");
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.ReceiptItem", b =>
                {
                    b.HasOne("MarketStack.Data.Contracts.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketStack.Data.Contracts.Entities.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.ReceiptTotal", b =>
                {
                    b.HasOne("MarketStack.Data.Contracts.Entities.Receipt", null)
                        .WithOne()
                        .HasForeignKey("MarketStack.Data.Contracts.Entities.ReceiptTotal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.StoreLocation", b =>
                {
                    b.HasOne("MarketStack.Data.Contracts.Entities.StoreChain", "StoreChain")
                        .WithMany("Locations")
                        .HasForeignKey("StoreChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreChain");
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.Receipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.StoreChain", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MarketStack.Data.Contracts.Entities.StoreLocation", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
